SELECT L.ACRONYM, FLOOR(SUM(V.VOTES)/SUM(L.SEATS)) AS ANVS
FROM LISTS L
JOIN MUNICIPALITIES M ON M.DISTRICT=L.DISTRICT
JOIN PARISHES P ON P.MUNICIPALITY=M.CODE
JOIN VOTINGS V ON V.PARISH=P.CODE
WHERE V.PARTY=L.PARTY
GROUP BY L.ACRONYM
ORDER BY ANVS DESC;