WITH 
MUN_PER_DIST AS (
    SELECT D.CODE, COUNT(M.CODE) AS TOTAL
    FROM DISTRICTS D
    JOIN MUNICIPALITIES M ON M.DISTRICT=D.CODE
    GROUP BY D.CODE
),
CDS_VOTES AS (
    SELECT D.CODE AS DISTRICT, M.CODE AS MUNICIPALITY, SUM(V.VOTES) AS CDSVOTES
    FROM DISTRICTS D
    JOIN MUNICIPALITIES M ON M.DISTRICT=D.CODE
    JOIN PARISHES P ON P.MUNICIPALITY=M.CODE
    JOIN VOTINGS V ON V.PARISH=P.CODE
    WHERE V.PARTY='CDSPP'
    GROUP BY D.CODE, M.CODE
),
PCP_VOTES AS (
    SELECT D.CODE AS DISTRICT, M.CODE AS MUNICIPALITY, SUM(V.VOTES) AS PCPVOTES
    FROM DISTRICTS D
    JOIN MUNICIPALITIES M ON M.DISTRICT=D.CODE
    JOIN PARISHES P ON P.MUNICIPALITY=M.CODE
    JOIN VOTINGS V ON V.PARISH=P.CODE
    WHERE V.PARTY='PCPPEV'
    GROUP BY D.CODE, M.CODE
),
CDS_MORE_THAN_PCP AS (
    SELECT CDS.DISTRICT, COUNT(CDS.MUNICIPALITY) AS COUNT
    FROM CDS_VOTES CDS
    JOIN PCP_VOTES PCP ON PCP.DISTRICT=CDS.DISTRICT
    WHERE CDS.CDSVOTES > PCP.PCPVOTES
    GROUP BY CDS.DISTRICT
)

SELECT D.CODE 
FROM MUN_PER_DIST D
WHERE (D.CODE, D.TOTAL) IN (
    SELECT C.DISTRICT, C.COUNT
    FROM CDS_MORE_THAN_PCP C
)
ORDER BY D.CODE;