WITH 
MUN_MORE_TWENTY AS(
    SELECT M.NAME, M.DISTRICT, COUNT(P.CODE) AS TOTAL
    GROUP BY M.NAME, M.DISTRICT
    HAVING COUNT(P.CODE) >20
),
MUNICIPALITIES_PER_DISTRICT AS (
    SELECT D.CODE, D.NAME, COUNT(M.CODE) AS TOTAL
    FROM DISTRICTS D
    JOIN MUNICIPALITIES M ON M.DISTRICT= D.CODE
    GROUP BY D.CODE, D.NAME
)
SELECT M.NAME AS MNAME, MPD.NAME AS DNAME, M.TOTAL AS TOTAL
FROM MUN_MORE_TWENTY M
JOIN MUNICIPALITIES_PER_DISTRICT MPD ON MPD.CODE = M.DISTRICT
WHERE M.TOTAL = MPD.TOTAL
ORDER BY M.NAME;
