WITH 
SEATS_PER_DISTRICT AS (

SELECT D.NAME, SUM(D.SEATS) AS SUM
FROM DISTRICTS D
JOIN LISTS L ON D.CODE = L.DISTRICT
GROUP BY D.CODE
ORDER BY SUM(D.SEATS) DESC
LIMIT 1 OFFSET 4;

)
SELECT D.NAME
FROM SEATS_PER_DISTRICT D;