WITH
VOTES_PARTY_PARISH AS (
    SELECT V.PARISH, V.PARTY, SUM(V.VOTES) AS TOTAL
    FROM VOTINGS V
    GROUP BY V.PARISH, V.PARTY
    HAVING SUM(V.VOTES)>1000
)
SELECT V.PARTY, COUNT(*) AS NPARISHES
FROM VOTES_PARTY_PARISH V
GROUP BY V.PARTY
ORDER BY NPARISHES DESC;