WITH
COUNT_PARISHES AS (

    SELECT D.CODE, COUNT(P.CODE) AS COUNT_PARISHES
    FROM DISTRICTS D 
    JOIN MUNICIPALITIES M ON M.DISTRICT=D.CODE
    JOIN PARISHES P ON P.MUNICIPALITY = M.CODE
    WHERE D.NAME='Lisboa'
    GROUP BY D.CODE
),
MUNICIPALITIES_LISBOA AS (
    SELECT D.CODE, COUNT(M.CODE) AS COUNT_MUNIS
    FROM DISTRICTS D 
    JOIN MUNICIPALITIES M ON M.DISTRICT=D.CODE
    WHERE D.NAME='Lisboa'
    GROUP BY D.CODE
)
SELECT P.COUNT_PARISHES*1.0 / M.COUNT_MUNIS AS MEDIA
FROM COUNT_PARISHES P
JOIN COUNT_MUNIS M ON P.CODE=M.CODE; 
