WITH
CDS_MUNIS AS (
    SELECT M.CODE, SUM(V.VOTES) AS VOTES 
    FROM VOTINGS V
    JOIN PARISHES P ON P.CODE=V.PARISH
    JOIN MUNICIPALITIES M ON M.CODE=PARISH.MUNICIPALITY    
    WHERE V.PARTY='CDSPP'
    GROUP BY M.CODE

),
PCP_MUNIS AS (
    SELECT M.CODE, SUM(V.VOTES) AS VOTES 
    FROM VOTINGS V
    JOIN PARISHES P ON P.CODE=V.PARISH
    JOIN MUNICIPALITIES M ON M.CODE=PARISH.MUNICIPALITY    
    WHERE V.PARTY='PCPPEV'
    GROUP BY M.CODE
)
SELECT COUNT(*) AS M 
FROM CDS_MUNIS CDS
JOIN PCP_MUNIS PCP ON CDS.CODE=PCP.CODE
WHERE CDS.VOTES > PCP.VOTES;