CREATE VIEW AMIZADETRANSITIVA AS:
    SELECT E1.ID, E3.ID
    FROM ESTUDANTE E1
    JOIN AMIZADE A1 ON A1.ID1=E1.ID
    JOIN ESTUDANTE E2 ON A1.ID2=E2.ID
    JOIN AMIZADE A2 ON A2.ID1 = E2.ID
    JOIN ESTUDANTE E3 ON E3.ID=A2.ID2
    WHERE E3.ID <> E1.ID