CREATE TRIGGER AMIZADE_INSERT
AFTER INSERT ON AMIZADE
FOR EACH ROW
BEGIN 
    IF NOT EXISTS (
        SELECT 1
        FROM AMIZADE
        WHERE ID1 = NEW.ID2 AND ID2=NEW.ID1
    ) THEN 
        INSERT INTO AMIZADE(ID1,ID2) VALUES (NEW.ID2, NEW.ID1)
    END IF;
END;

CREATE TRIGGER AMIZADE_DELETE
AFTER DELETE ON AMIZADE
FOR EACH ROW
BEGIN
    DELETE FROM AMIZADE
    WHERE (ID1=OLD.ID2 AND ID2 = OLD.ID1);
END;