SELECT E.NAME, E.ANO
FROM ESTUDANTE E
JOIN AMIZADE A ON E.ID=A.ID1
GROUP BY E.NAME, E.ANO
HAVING COUNT(*) = (
    SELECT MAX(FRIENDS)
    FROM (
        SELECT ID1, COUNT(*) AS FRIENDS
        FROM AMIZADE 
        GROUP BY ID1
    ) AS COUNTS
);

-------or--------

WITH
FRIENDSHIPS AS(
    SELECT ID1, COUNT(*) AS FRIENDS
    FROM AMIZADE
    GROUP BY ID1
),
MAX_FRIENDS AS (
    SELECT ID1
    FROM FRIENDSHIPS
    WHERE FRIENDS = (
        SELECT MAX(FRIENDS)
        FROM FRIENDSHIPS
    )
)
SELECT E.NAME, E.ANO
FROM ESTUDANTE E
JOIN MAX_FRIENDS M ON M.ID1=E.ID 