WITH
FRIENDSHIPS AS(
SELECT E.ID, COUNT(*) AS FRIENDSHIPS
FROM ESTUDANTE E
JOIN AMIZADE A ON A.ID1=E.ID
GROUP BY E.ID
)

SELECT E.NAME
FROM ESTUDANTE E 
JOIN FRIENDSHIPS F ON F.ID=E.ID
WHERE F.FRIENDSHIPS >3;