WITH 
VOTES_PARTY_MUNICIPALITY AS(
    SELECT M.DISTRICT, M.CODE, V.PARTY, SUM(V.VOTES) AS VOTES
    FROM VOTINGS V 
    JOIN PARISHES P ON P.CODE = V.PARISH
    JOIN MUNICIPALITIES M ON M.CODE = P.MUNICIPALITY
    GROUP BY  M.DISTRICT, M.CODE, V.PARTY
),
WINNER_MUNICIPALITY AS (
    SELECT *
    FROM VOTES_PARTY_MUNICIPALITY VPM
    WHERE VPM.VOTES = (
        SELECT MAX(VOTES)
        FROM VOTES_PARTY_MUNICIPALITY 
        WHERE VPM.CODE= CODE
    )
),
MUNICIPALITIES_PER_DISTRICT AS (
    SELECT D.NAME, COUNT(*) AS COUNT
    FROM DISTRICTS D
    JOIN MUNICIPALITIES M ON M.DISTRICT=D.CODE
    GROUP BY D.NAME
),
WINNER_PER_DISTRICT AS (
    SELECT D.CODE,D.NAME,WM.PARTY, COUNT(*) AS COUNT
    FROM WINNER_MUNICIPALITY WM
    JOIN DISTRICTS D ON D.CODE = WM.DISTRICT
    GROUP BY D.NAME, WM.PARTY
)
SELECT WD.CODE, WD.NAME,WD.PARTY
FROM WINNER_PER_DISTRICT WD
WHERE (WD.NAME, WD.COUNT) IN MUNICIPALITIES_PER_DISTRICT
