CREATE VIEW M1COUNT AS 
    SELECT D.CODE AS 'D', M.NAME, COUNT(P.CODE) AS 'PARISHES_COUNT'
    FROM DISTRICTS D
    JOIN MUNICIPALITIES M ON M.DISTRICT = D.CODE
    JOIN PARISHES P ON P.MUNICIPALITY=M.CODE
    GROUP BY D.CODE, M.NAME;
    
CREATE VIEW M2COUNT AS 
    SELECT D.CODE AS 'D', M.NAME, COUNT(P.CODE) AS 'PARISHES_COUNT'
    FROM DISTRICTS D
    JOIN MUNICIPALITIES M ON M.DISTRICT = D.CODE
    JOIN PARISHES P ON P.MUNICIPALITY=M.CODE
    GROUP BY D.CODE, M.NAME;

SELECT D.CODE, M1C.NAME AS 'namea', M2C.NAME AS 'nameb', M1C.PARISHES_COUNT
FROM DISTRICTS D
JOIN M1COUNT M1C ON M1C.D=D.CODE
JOIN M2COUNT M2C ON M2C.D=D.CODE
WHERE M1C.D=M2C.D
AND M1C.NAME<M2C.NAME
AND M1C.PARISHES_COUNT=M2C.PARISHES_COUNT

