SELECT P.ACRONYM, P.DESIGNATION
FROM PARTIES P
WHERE P.ACRONYM NOT IN (
    SELECT V.PARTY
    FROM VOTINGS V
    JOIN PARISHES P ON P.CODE=V.PARISH
    JOIN MUNICIPALITIES M ON M.CODE=P.MUNICIPALITY
    JOIN DISTRICTS D ON D.CODE = M.DISTRICT
    WHERE D.NAME ='Lisboa' )
ORDER BY P.ACRONYM ASC;