SELECT D.CODE, D.NAME, V.PARTY, SUM(V.VOTES) AS 'VOTES'
FROM VOTINGS V
JOIN PARISHES P ON P.CODE = V.PARISH
JOIN MUNICIPALITIES M ON M.CODE = P.MUNICIPALITY
JOIN DISTRICTS D ON D.CODE = M.DISTRICT
GROUP BY D.CODE, D.NAME, V.PARTY
ORDER BY D.CODE ASC, V.PARTY ASC

