SELECT M.NAME
FROM MUNICIPALITIES M
WHERE M.DISTRICT = (
    SELECT D.CODE
    FROM DISTRICTS D
    JOIN PARTICIPATIONS P ON P.DISTRICT=D.CODE
    WHERE P.VOTERS = (
        SELECT MAX(P.VOTERS)
        FROM PARTICIPATIONS P
    )
);