CREATE VIEW DISTRICTVOTES AS
  SELECT D.NAME, PARTY.DESIGNATION, SUM(V.VOTES) AS 'VOTES'
  FROM DISTRICTS D
  JOIN MUNICIPALITIES M ON D.CODE=M.DISTRICT
  JOIN PARISHES P ON M.CODE=P.MUNICIPALITY
  JOIN VOTINGS V ON V.PARISH = P.CODE
  JOIN PARTIES PARTY ON PARTY.ACRONYM = V.PARTY
  GROUP BY D.NAME, PARTY.DESIGNATION
  ORDER BY D.NAME ASC;
    
SELECT V.NAME, V.DESIGNATION, V.VOTES
FROM DISTRICTVOTES V
WHERE (V.NAME, V.VOTES) IN (
  SELECT V.NAME, MAX(V.VOTES)
  FROM DISTRICTVOTES V
  GROUP BY V.NAME
)
ORDER BY V.NAME;