CREATE VIEW ParishWINNER AS
  SELECT V.PARISH, V.PARTY
  FROM VOTINGS V
  WHERE (V.PARISH, V.VOTES) IN (
    SELECT V.PARISH, MAX(V.VOTES)
    FROM VOTINGS V
    GROUP BY V.PARISH
  );
SELECT M.CODE, M.NAME, PW.PARTY
FROM ParishWINNER PW
JOIN PARISHES P ON PW.PARISH = P.CODE
JOIN MUNICIPALITIES M ON M.CODE = P.MUNICIPALITY
JOIN DISTRICTS D ON D.CODE = M.DISTRICT
WHERE D.NAME = 'Porto'
GROUP BY M.CODE, M.NAME, PW.PARTY
HAVING COUNT(PW.PARISH) = (
  SELECT COUNT(*)
  FROM PARISHES PX
  WHERE PX.MUNICIPALITY = M.CODE
)
ORDER BY M.CODE ASC, PW.PARTY ASC;