SELECT V.PARTY, D.NAME, SUM(V.VOTES), L.SEATS, ROUND(SUM(V.VOTES)/L.SEATS,0) AS 'VOTES_PER_DEPUTY'
FROM VOTINGS V
JOIN PARISHES P ON P.CODE=V.PARISH
JOIN MUNICIPALITIES M ON M.CODE=P.MUNICIPALITY
JOIN DISTRICTS D ON D.CODE = M.DISTRICT
JOIN LISTS L ON L.DISTRICT = D.CODE AND V.PARTY=L.PARTY
WHERE L.SEATS>0
GROUP BY V.PARTY, D.NAME, L.SEATS
ORDER BY VOTES_PER_DEPUTY;