WITH
THIRD_MUNICIPALITY AS (
    SELECT P.MUNICIPALITY, SUM(V.VOTES) AS TOTAL
    FROM PARISHES P 
    JOIN VOTINGS V ON V.PARISH=P.CODE
    GROUP BY P.MUNICIPALITY
    ORDER BY TOTAL DESC
    LIMIT 1 OFFSET 2
)
SELECT V.PARTY, SUM(V.VOTES) AS VOTES 
FROM VOTINGS V 
JOIN PARISHES P ON P.CODE= V.PARISH
WHERE P.MUNICIPALITY = (
    SELECT MUNICIPALITY 
    FROM THIRD_MUNICIPALITY 
)
GROUP BY V.PARTY
ORDER BY VOTES ASC
LIMIT 1;