SELECT D.NAME, COUNT(P.CODE) AS TOTAL
FROM DISTRICTS D 
LEFT JOIN MUNICIPALITIES M ON M.DISTRICT=D.CODE
LEFT JOIN PARISHES P ON M.CODE= P.MUNICIPALITY
WHERE P.NAME='Nogueira'
GROUP BY D.NAME
ORDER BY D.NAME;